version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/Montreal"
    open-pull-requests-limit: 10
    assignees:
      - "SteaceP"
    labels:
      - "dependencies"
    rebase-strategy: "auto"

    groups:
      all-npm-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "vitest"
        versions: [">= 4.0.0"]
      - dependency-name: "@vitest/*"
        versions: [">= 4.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/Montreal"
    open-pull-requests-limit: 5
    assignees:
      - "SteaceP"
    labels:
      - "dependencies"
    rebase-strategy: "auto"

    groups:
      all-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "actions/checkout"
      - dependency-name: "actions/setup-node"
